INSERT INTO ESTADO(ID, UF, REGIAO) VALUES(1, 'DF','CO');
INSERT INTO MUNICIPIO(ID, ESTADO_ID, NOME) VALUES(1,1,'BRASILIA');
INSERT INTO REVENDA(ID, MUNICIPIO_ID, NOME, CNPJ, BANDEIRA) 
 VALUES(1,1, 'ABRITTA POSTOS DE SERVIÇOS LTDA','10668863000195','RAIZEN');